//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Nullable<int> IDRole { get; set; }
        public string UserName { get; set; }
        public string UserLastName { get; set; }
        public string UserOtherName { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
